name: Run Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
       - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

       - uses: actions/checkout@v4
        with:
          python-version: 3.8

      - run: |
          python -m unittest discover -s tests -p "test_*.py"
